name: Python package

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.7", "3.8", "3.9", "3.10"]
        steps:
          - uses: actions/checkout@v3
          - name: executing remote ssh commands using password
            uses: appleboy/ssh-action@master
            with:
                host: 172.104.225.128
                username: root
                password: ${{ secrets.PASSWORD }}
                port: 22
                script: |
                    cd /root/microservices
                    git pull
                    source venv/bin/activate
                    pip install -r requirements.txt
